### PR TITLE
Call appropriate sockname function for socket type

### PR DESCRIPTION
**Pull request by jaydoane**
COUCHDB: 3049

### CODE REVIEW

**Comment by kxepal** [comment]
+1

**Comment by jaydoane** [comment]
BTW, are we delaying merge until after 2.0 code freeze?

**Comment by kxepal** [comment]
I don't think that "code freeze" also means "bug fix freeze". Especially, for already well known existed functionality.

**Comment by jaydoane** [comment]
Ok, can you merge for me?

**Comment by kxepal** [comment]
@jaydoane done. Thanks!

**Comment by kxepal** [comment]
@rnewson Well, this PR applies changes for the case when Host header is not present. What kind of function_clause happens and where?

**Pull request merged**
