### PR TITLE
Fix dispatch to handle_error EPI hook

### PR DESCRIPTION
**Pull request by iilyak**

### CODE REVIEW

**Comment by eiri** [comment]
Just a short note on what it does, please?

**Comment by kxepal** [comment]
I think it's a copy-paste fix of wrong hook usage to catch the errors over epi.
+1

**Comment by eiri** [comment]
Ah, ok, so this is so the plugins get called on `handle_error` callback with chttpd's errors instead of `after_request`, if I read code correctly.
+1

**Comment by eiri** [comment]
those Russian devs, they never answer, just gloomy carry on :guardsman:

**Comment by kxepal** [comment]
@eiri 
In Soviet Russia only KGB can get the answers from you! P:

**Comment by iilyak** [comment]
@eiri: I thought that you were satisfied with @kxepal explanation. You also provided a correct explanation yourself here https://github.com/apache/couchdb-chttpd/pull/105#issuecomment-193897222. Going forward I will provide a short explanations for PRs.

**Comment by eiri** [comment]
@iilyak cool, thank you! sorry for been grumpy, it just I've spent so much time in git's blame on mrview, trying to understand _whys_, that I came to really value a good explanation on PR and always trying to do that for sake of some poor soul that'd come to look at my code in five years.

**Pull request merged**
