### PR TITLE
3049 fix sockname

### PR DESCRIPTION
**Pull request by jaydoane**
@rnewson, @iilyak

### CODE REVIEW

**Comment by rnewson** [comment]
+1

**Comment by kxepal** [comment]
So technically the fix of existed code should be:
```
sockname({ssl, Socket}) ->
    ssl:sockname(Socket).
```
?

**Comment by kxepal** [comment]
/:

**Comment by jaydoane** [comment]
Yes, I seem to have tested that code snippet on a non-mochiweb socket (without the tuple), which is utterly my bad :(

**Comment by rnewson** [comment]
@kxepal The new code reflects exactly what couchdb has always done since 2012 (that code is in couch_httpd.erl).

**Comment by kxepal** [comment]
@rnewson that doesn't means that it couldn't be improved (;

**Comment by kxepal** [comment]
But it's too late anyway, so ok.

**Comment by rnewson** [comment]
We'd want them to match, though. In my opinion the version in couch_httpd is quite clear.

**Comment by rnewson** [comment]
@kxepal I hope it's also clear that the socket is _never_ a pid, that's the mistake, it's a port in the non-ssl case and a tuple, {ssl, blah, port, ...} if ssl.

**Comment by kxepal** [comment]
@rnewson yes, you're right here.

**Pull request merged**
