### PR TITLE
Use illegal_docid error for really bad document ids

### PR DESCRIPTION
**Pull request by kxepal**

### CODE REVIEW

**Comment by kxepal** [comment]
See also: https://github.com/apache/couchdb-couch/pull/101

**Comment by tonysun83** [comment]
just curious why we're adding an extra match here in addition to this change:

https://github.com/apache/couchdb-chttpd/pull/73/files

**Comment by kxepal** [comment]
@tonysun83 

First match `{illegal_docid, Reason}` is for direct `couch_doc:validate_docid/1` call.
Second match goes for all_docs view and caused by some fabric internals. I didn't found where and why it's so awkward.

**Comment by tonysun83** [comment]
ah, from the other PR you referenced above. I see it now.
+1.

**Comment by rnewson** [comment]
+1

**Pull request merged**
