### PR TITLE
handle_system_req Memory includes total

### PR DESCRIPTION
**Pull request by jcounts**
@rnewson 

Originally was done here: https://github.com/cloudant/chttpd

moved to this repo

### CODE REVIEW

**Comment by kxepal** [comment]
How can I trigger this handler via HTTP API? So far I see there is no place in code that makes it available to handle incoming requests.

**Comment by rnewson** [comment]
@kxepal: does seem to be missing from https://github.com/apache/couchdb-chttpd/blob/master/src/chttpd_httpd_handlers.erl :/

**Comment by kxepal** [comment]
@rnewson Yes, I noticed that, but commentary for the handler says that it's only available for backdoor interface...or at least it should be.

I'll add it to default.ini where global httpd handlers are defined and ensure what it's available by `/_node/X/_system` path on cluster interface, ok?

**Comment by rnewson** [comment]
ah, quite right. Let's just add it to :5986 for now

**Comment by rnewson** [comment]
actually /_system is available on both front and back ports at Cloudant, I just checked, so we should do the same.

**Comment by kxepal** [comment]
@rnewson ok, I'll made PRs for this.

**Comment by kxepal** [comment]
Hm, not sure what's use case for this patch. Example output:
```
    "memory": {
        "atom": 801697,
        "atom_used": 793412,
        "binary": 1656328,
        "code": 23299745,
        "ets": 1753608,
        "other": -36439634,
        "processes": 8933048,
        "processes_used": 8919640
    }
```
Notice negative other value. I believe, total value should be shows with separate object field.

**Comment by jcounts** [comment]
hmm...I wasn't sure if this would solve my problem or not. This was a response for:
https://cloudant.fogbugz.com/f/cases/47888/DBcore-memory-usage-displayed-in-admin-dashboard-is-wrong

Which is a bug in:
https://github.com/cloudant/wilson/blob/develop/wilson/views/clusters.py

The Wilson endpoint pulls info from graphite (and haproxy).

**Comment by kxepal** [comment]
@jcounts Sorry, I don't have access to Cloudant fogbugz and private repositories. What's the case there is short which is fine to gather negative memory values?

**Comment by kxepal** [comment]
@jcounts also, how about to backport those fogbugz ticket to CouchDB JIRA and bound it with this commit? Would be helpful to track the things.

**Pull request closed without merging**
